pipeline {
    agent any
    
    stages {
        stage('Master_Branch') {
            steps {
                echo "THIS IS WEEK6 HOMEWORK. BRANCH1_WK6 BRANCH................!!!"
                }
        }
    }
}
